name = "RegressionDiscontinuity"
uuid = "5f6169ef-b865-4e89-817c-551391b0abce"
authors = ["Nikos Ignatiadis <nikos.ignatiadis01@gmail.com> and contributors"]
version = "0.1.0"

[deps]
CodecBzip2 = "523fee87-0ab8-5b00-afb7-3ecf72e48cfd"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
RData = "df47a6cb-8c03-5eed-afd8-b6050d6c41da"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
CodecBzip2 = "0.7"
DataFrames = "0.20, 0.21"
Distributions = "0.23"
GLM = "1.3"
RData = "0.7"
RecipesBase = "1.1"
StatsBase = "0.33"
StatsModels = "0.6"
Tables = "1.0"
UnPack = "1.0"
julia = "1.4, 1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
